### ISSUE TITLE
Requirements conflict

### ISSUE THREAD

**Issue by TKELKAR123** [pipecat-ai/pipecat#863] opened 2024-12-15 01:06 UTC
# Description
Is this reporting a bug or feature request?

Bug

If reporting a bug, please fill out the following:

### Environment
- pipecat-ai version:
- python version: 3.13.1
- OS: Windows 11

### Issue description
Provide a clear description of the issue.

Can't do the normal requirements.txt file for the simple-chatbot because of this:
```
ERROR: Cannot install pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.10, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.11, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.12, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.13, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.14, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.15, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.16, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.17, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.18, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.19, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.20, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.21, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.22, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.23, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.24, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.25, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.26, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.27, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.28, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.29, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.30, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.31, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.32, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.33, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.34, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.35, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.36, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.37, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.38, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.39, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.40, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.41, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.42, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.43, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.44, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.45, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.46, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.47, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.48, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.49, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.50 and pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.50 depends on daily-python~=0.13.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.49 depends on daily-python~=0.13.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.48 depends on daily-python~=0.12.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.47 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.46 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.45 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.44 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.43 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.42 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.41 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.40 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.39 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.38 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.37 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.36 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.35 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.34 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.33 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.32 depends on daily-python~=0.10.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.31 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.30 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.29 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.28 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.27 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.26 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.25 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.24 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.23 depends on daily-python~=0.8.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.22 depends on daily-python~=0.8.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.21 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.20 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.19 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.18 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.17 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.16 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.15 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.14 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.13 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.12 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.11 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.10 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.9 depends on daily-python~=0.7.4; extra == "daily"      

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### Repro steps
List the steps to reproduce the issue.
Do a virtual environment
Get the above error

### Expected behavior
Installs

### Actual behavior
Doesn't install
### Logs

ERROR: Cannot install pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.10, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.11, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.12, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.13, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.14, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.15, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.16, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.17, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.18, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.19, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.20, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.21, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.22, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.23, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.24, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.25, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.26, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.27, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.28, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.29, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.30, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.31, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.32, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.33, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.34, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.35, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.36, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.37, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.38, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.39, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.40, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.41, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.42, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.43, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.44, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.45, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.46, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.47, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.48, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.49, pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.50 and pipecat-ai[daily,elevenlabs,google,openai,silero]==0.0.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.50 depends on daily-python~=0.13.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.49 depends on daily-python~=0.13.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.48 depends on daily-python~=0.12.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.47 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.46 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.45 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.44 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.43 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.42 depends on daily-python~=0.11.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.41 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.40 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.39 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.38 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.37 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.36 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.35 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.34 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.33 depends on daily-python~=0.10.1; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.32 depends on daily-python~=0.10.0; extra == "daily"    
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.31 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.30 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.29 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.28 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.27 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.26 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.25 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.24 depends on daily-python~=0.9.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.23 depends on daily-python~=0.8.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.22 depends on daily-python~=0.8.0; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.21 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.20 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.19 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.18 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.17 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.16 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.15 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.14 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.13 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.12 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.11 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.10 depends on daily-python~=0.7.4; extra == "daily"     
    pipecat-ai[daily,elevenlabs,google,openai,silero] 0.0.9 depends on daily-python~=0.7.4; extra == "daily"      

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by aconchillo** [comment] 2024-12-15 18:16
Duplicate of https://github.com/pipecat-ai/pipecat/issues/290.

Current solution is to use WSL on Windows.

**Closed by aconchillo** 2024-12-15 18:16 UTC

**Comment by ballariadarsh09** [comment] 2025-02-21 15:23
But what is WSL how should i use it . Please let me know @aconchillo
