### ISSUE TITLE
Dependency Resolution Conflict for pipecat-ai[daily]

### ISSUE THREAD

**Issue by donadlsa** [pipecat-ai/pipecat#759] opened 2024-11-29 03:39 UTC
# Description
Is this reporting a bug or feature request?
Bug

If reporting a bug, please fill out the following:

### Environment
- pipecat-ai version: 0.0.49
- python version: Python 3.12.7
- OS: Windows 11 Home

### Issue description
The installation of pipecat-ai[daily] fails due to conflicting dependency versions for the required daily-python package. The issue arises because different versions of pipecat-ai[daily] require incompatible versions of daily-python.

Example of conflicting dependencies:
pipecat-ai[daily]==0.0.49 requires daily-python~=0.13.0
pipecat-ai[daily]==0.0.48 requires daily-python~=0.12.0
Earlier versions require even older incompatible versions.

Severity:
High: Blocks installation of required dependencies for the project.

Priority:
Immediate: Resolving this is necessary for project progress.

### Repro steps
Activate the virtual environment.
Run the command:
pip install "pipecat-ai[daily]"

### Expected behavior
The package pipecat-ai[daily] should install successfully without any dependency resolution issues.

### Actual behavior
Pip enters a prolonged backtracking process, attempting to resolve dependency conflicts.
Installation ultimately fails with the following error:

ERROR: Cannot install pipecat-ai[daily] == <version range> due to conflicting dependencies.
The error message suggests version conflicts among pipecat-ai[daily] and its dependency daily-python.

### Logs
INFO: pip is looking at multiple versions of pipecat-ai[daily] to determine which version is compatible with other requirements. This could take a while.
Collecting pipecat-ai[daily]
  Using cached pipecat_ai-0.0.48-py3-none-any.whl.metadata (13 kB)
  Using cached pipecat_ai-0.0.47-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: scipy~=1.14.1 in c:\...\venv\lib\site-packages (from pipecat-ai[daily]) (1.14.1)
  Using cached pipecat_ai-0.0.46-py3-none-any.whl.metadata (12 kB)
  Using cached pipecat_ai-0.0.45-py3-none-any.whl.metadata (12 kB)
  Using cached pipecat_ai-0.0.44-py3-none-any.whl.metadata (12 kB)
  Using cached pipecat_ai-0.0.43-py3-none-any.whl.metadata (12 kB)
  Using cached pipecat_ai-0.0.42-py3-none-any.whl.metadata (12 kB)
INFO: pip is still looking at multiple versions of pipecat-ai[daily] to determine which version is compatible with other requirements. This could take a while.
  Using cached pipecat_ai-0.0.41-py3-none-any.whl.metadata (12 kB)
  Using cached pipecat_ai-0.0.40-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.39-py3-none-any.whl.metadata (11 kB)
Collecting aiohttp~=3.9.5 (from pipecat-ai[daily])
  Using cached aiohttp-3.9.5-cp312-cp312-win_amd64.whl.metadata (7.7 kB)
Collecting Pillow~=10.3.0 (from pipecat-ai[daily])
  Using cached pillow-10.3.0-cp312-cp312-win_amd64.whl.metadata (9.4 kB)
Requirement already satisfied: typing-extensions~=4.12.1 in c:\...\venv\lib\site-packages (from pipecat-ai[daily]) (4.12.2)
Collecting pipecat-ai[daily]
  Using cached pipecat_ai-0.0.38-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.37-py3-none-any.whl.metadata (11 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached pipecat_ai-0.0.36-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.35-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.34-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.33-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.32-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.31-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.30-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.29-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.28-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.27-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.26-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.25-py3-none-any.whl.metadata (11 kB)
Collecting typing-extensions~=4.11.0 (from pipecat-ai[daily])
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting pipecat-ai[daily]
  Using cached pipecat_ai-0.0.24-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.23-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.22-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.21-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.20-py3-none-any.whl.metadata (11 kB)
  Using cached pipecat_ai-0.0.19-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.18-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.17-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.16-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.15-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.14-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.13-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.12-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.11-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.10-py3-none-any.whl.metadata (10 kB)
  Using cached pipecat_ai-0.0.9-py3-none-any.whl.metadata (10 kB)
ERROR: Cannot install pipecat-ai[daily]==0.0.10, pipecat-ai[daily]==0.0.11, pipecat-ai[daily]==0.0.12, pipecat-ai[daily]==0.0.13, pipecat-ai[daily]==0.0.14, pipecat-ai[daily]==0.0.15, pipecat-ai[daily]==0.0.16, pipecat-ai[daily]==0.0.17, pipecat-ai[daily]==0.0.18, pipecat-ai[daily]==0.0.19, pipecat-ai[daily]==0.0.20, pipecat-ai[daily]==0.0.21, pipecat-ai[daily]==0.0.22, pipecat-ai[daily]==0.0.23, pipecat-ai[daily]==0.0.24, pipecat-ai[daily]==0.0.25, pipecat-ai[daily]==0.0.26, pipecat-ai[daily]==0.0.27, pipecat-ai[daily]==0.0.28, pipecat-ai[daily]==0.0.29, pipecat-ai[daily]==0.0.30, pipecat-ai[daily]==0.0.31, pipecat-ai[daily]==0.0.32, pipecat-ai[daily]==0.0.33, pipecat-ai[daily]==0.0.34, pipecat-ai[daily]==0.0.35, pipecat-ai[daily]==0.0.36, pipecat-ai[daily]==0.0.37, pipecat-ai[daily]==0.0.38, pipecat-ai[daily]==0.0.39, pipecat-ai[daily]==0.0.40, pipecat-ai[daily]==0.0.41, pipecat-ai[daily]==0.0.42, pipecat-ai[daily]==0.0.43, pipecat-ai[daily]==0.0.44, pipecat-ai[daily]==0.0.45, pipecat-ai[daily]==0.0.46, pipecat-ai[daily]==0.0.47, pipecat-ai[daily]==0.0.48, pipecat-ai[daily]==0.0.49 and pipecat-ai[daily]==0.0.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    pipecat-ai[daily] 0.0.49 depends on daily-python~=0.13.0; extra == "daily"
    pipecat-ai[daily] 0.0.48 depends on daily-python~=0.12.0; extra == "daily"
    pipecat-ai[daily] 0.0.47 depends on daily-python~=0.11.0; extra == "daily"
    pipecat-ai[daily] 0.0.46 depends on daily-python~=0.11.0; extra == "daily"
    pipecat-ai[daily] 0.0.45 depends on daily-python~=0.11.0; extra == "daily"
    pipecat-ai[daily] 0.0.44 depends on daily-python~=0.11.0; extra == "daily"
    pipecat-ai[daily] 0.0.43 depends on daily-python~=0.11.0; extra == "daily"
    pipecat-ai[daily] 0.0.42 depends on daily-python~=0.11.0; extra == "daily"
    pipecat-ai[daily] 0.0.41 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.40 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.39 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.38 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.37 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.36 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.35 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.34 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.33 depends on daily-python~=0.10.1; extra == "daily"
    pipecat-ai[daily] 0.0.32 depends on daily-python~=0.10.0; extra == "daily"
    pipecat-ai[daily] 0.0.31 depends on daily-python~=0.9.0; extra == "daily"
    pipecat-ai[daily] 0.0.30 depends on daily-python~=0.9.0; extra == "daily"
    pipecat-ai[daily] 0.0.29 depends on daily-python~=0.9.0; extra == "daily"
    pipecat-ai[daily] 0.0.28 depends on daily-python~=0.9.0; extra == "daily"
    pipecat-ai[daily] 0.0.27 depends on daily-python~=0.9.0; extra == "daily"
    pipecat-ai[daily] 0.0.26 depends on daily-python~=0.9.0; extra == "daily"
    pipecat-ai[daily] 0.0.25 depends on daily-python~=0.9.0; extra == "daily"
    pipecat-ai[daily] 0.0.24 depends on daily-python~=0.9.0; extra == "daily"
    pipecat-ai[daily] 0.0.23 depends on daily-python~=0.8.0; extra == "daily"
    pipecat-ai[daily] 0.0.22 depends on daily-python~=0.8.0; extra == "daily"
    pipecat-ai[daily] 0.0.21 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.20 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.19 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.18 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.17 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.16 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.15 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.14 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.13 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.12 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.11 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.10 depends on daily-python~=0.7.4; extra == "daily"
    pipecat-ai[daily] 0.0.9 depends on daily-python~=0.7.4; extra == "daily"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by aconchillo** [comment] 2024-12-05 03:37
Closing, duplicate of #290 . Hopefully, `daily-python` will have support for Windows early 2025. Until then an option is to use Windows WSL.

**Closed by aconchillo** 2024-12-05 03:37 UTC
