### ISSUE TITLE
`EndPipeFrame` class is used but not defined

### ISSUE THREAD

**Issue by amacapri** [pipecat-ai/pipecat#287] opened 2024-07-06 18:46 UTC
`EndPipeFrame` class does not exist, but it is referenced from `src/pipecat/pipeline/merge_pipeline.py` and `examples/foundational/04-utterance-and-speech.py`.

**Comment by jptaylor** [comment] 2024-07-07 02:26
Thank you. I think this a remnant and should be `EndFrame`. I think the foundational examples need a scan. Will try to get to this next week whilst we're updating docs.

**Comment by vipyne** [comment] 2024-10-21 23:42
I believe this is resolved.  closing the issue.

**Closed by vipyne** 2024-10-21 23:42 UTC

**Comment by dominikroblek** [comment] 2024-10-22 06:02
A quick search show the issue is not resolved:
https://github.com/search?q=repo%3Apipecat-ai%2Fpipecat%20EndPipeFrame&type=code

EndPipeFrame is not defined but still used by two examples.
