### ISSUE TITLE
error  "conflicting dependencies"  while install 

### ISSUE THREAD

**Issue by musexiaoluo** [pipecat-ai/pipecat#592] opened 2024-10-15 09:28 UTC
error  "conflicting dependencies"  while install  requirements.txt   in   simple-chatbot  ，how to resolve ?

![image](https://github.com/user-attachments/assets/21759d4a-905e-455c-a9c5-6b5461b6e479)

**Comment by vipyne** [comment] 2024-10-21 23:50
closing as this seems like a duplicate of #290 
@musexiaoluo feel free to add more detail (what platform you are using) to the issue thread there.
thanks.

**Closed by vipyne** 2024-10-21 23:50 UTC
